import { StyleSheet, Dimensions } from "react-native";

export const myStyles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: 'rgba(0, 0, 40, 0.8)',
  },
  backgroundImage: {
    opacity: 1,
  },
  titleContainer: {
    flex: 1,
    backgroundColor: "#1E2A47",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderRadius: 10,
    borderColor: "#6C7D94",
    marginVertical: 10,
    marginHorizontal: 20,
    flexDirection: "column",
  },
  text: {
    color: "#F3F4F8",
    fontSize: 24,
    letterSpacing: 2,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 5,
    textShadowColor: "rgba(255, 255, 255, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    lineHeight: 40,
    fontFamily: "Mountain",
  },
  navbuttonContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Dimensions.get("window").height * 0.01,
  },
  nnavButton: {
    marginHorizontal: 10,
    backgroundColor: "#F7C555", 
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#F3F4F8",
  },
  navButtonText: {
    color: "#1E2A47",
    fontSize: 18,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  scrollContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
  },
  rowContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
    margin: 5,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingBottom: 10,
    paddingHorizontal: 5,
    alignItems: "center",
  },
  dateContainer: {
    flex: 1,
    margin: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2B3C63",
    borderColor: "#F3F4F8",
    borderWidth: 2,
    borderRadius: 10,
    marginHorizontal: 10,
    maxHeight: "100%",
    maxWidth: "100%",
  },
  dateLabel1: {
    fontSize: 80,
    color: "#F3F4F8", 
    fontFamily: "Mountain",
    textShadowColor: "rgba(255, 255, 255, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  dateLabel2: {
    fontSize: 100,
    fontFamily: "Mountain",
    color: "#F3F4F8",
  },
  dateText1: {
    fontSize: 10,
    fontWeight: "bold",
    lineHeight: 40,
    textAlign: "center",
    letterSpacing: .5,
    color: "#F3F4F8", 
    textShadowColor: "rgba(255, 255, 255, 0.3)", 
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  dateText2: {
    fontSize: 10,
    fontWeight: "bold",
    lineHeight: 40,
    textAlign: "center",
    letterSpacing: .5,
    color: "#F3F4F8", 
  },
  dataTextContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 3,
    maxWidth: "100%",
  },
  centeredModalView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "#FFFFFF", 
    borderColor: "#6C7D94", 
    borderWidth: 4,
    borderRadius: 10,
    textShadowColor: "rgba(255, 255, 255, 0.3)", 
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    elevation: 5,
  },
  results: {
    textAlign: "center",
    color: "#F3F4F8", 
    fontFamily: "Mountain",
    textShadowColor: "rgba(255, 255, 255, 0.3)", 
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  resultsContainer: {
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2B3C63", 
    borderColor: "#F3F4F8", 
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 1,
    maxWidth: "100%",
    marginBottom: Dimensions.get("window").height * 0.01, 
    paddingTop: 1, 
  }
});
